---
- import_tasks: setup_users.yml

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install common apps
  apt:
    name: htop,curl,net-tools,ufw,fail2ban,unattended-upgrades,logwatch,vim

- import_tasks: security-tasks.yml

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: debugging reboot_required
  debug:
    var: reboot_required_file

- name: reboot
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "System reboot"
  async: 1
  poll: 0
  when: reboot_required_file.stat.exists

- name: debug vars
  debug:
    var: (ansible_ssh_host|default(ansible_host))|default(inventory_hostname)

- name: Wait for restart
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  connection: local
  when: reboot_required_file.stat.exists

- name: Copy Rsyslog Configuration File
  template: src=60-jsoninput.conf.j2 dest=/etc/rsyslog.d/60-jsoninput.conf mode=0644 force=yes
  register: system_change
  notify: restart rsyslog