---
- name: User shimmyt
  user:
    name: shimmyt
    state: present
    update_password: always
    password: "{{ shimmyt_user_password }}"
    shell: /bin/bash

- name: User ansible
  user:
    name: ansible
    state: present
    update_password: always
    password: "{{ ansible_user_password }}"
    shell: /bin/bash